package model;
// Generated May 12, 2020 12:37:21 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Book generated by hbm2java
 */
public class Book  implements java.io.Serializable {


     private String bookId;
     private Category category;
     private String title;
     private String phouse;
     private Date pdate;
     private String author;
     private Integer pages;
     private String category_1;

    public Book() {
    }

	
    public Book(String bookId) {
        this.bookId = bookId;
    }
    public Book(String bookId, Category category, String title, String phouse, Date pdate, String author, Integer pages, String category_1) {
       this.bookId = bookId;
       this.category = category;
       this.title = title;
       this.phouse = phouse;
       this.pdate = pdate;
       this.author = author;
       this.pages = pages;
       this.category_1 = category_1;
    }
   
    public String getBookId() {
        return this.bookId;
    }
    
    public void setBookId(String bookId) {
        this.bookId = bookId;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getPhouse() {
        return this.phouse;
    }
    
    public void setPhouse(String phouse) {
        this.phouse = phouse;
    }
    public Date getPdate() {
        return this.pdate;
    }
    
    public void setPdate(Date pdate) {
        this.pdate = pdate;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public Integer getPages() {
        return this.pages;
    }
    
    public void setPages(Integer pages) {
        this.pages = pages;
    }
    public String getCategory_1() {
        return this.category_1;
    }
    
    public void setCategory_1(String category_1) {
        this.category_1 = category_1;
    }




}


