package model;
// Generated May 12, 2020 12:37:21 AM by Hibernate Tools 4.3.1



/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private String regno;
     private String firstname;
     private String lastname;
     private String phone;
     private String email;
     private String category;
     private String photo;

    public Client() {
    }

	
    public Client(String regno) {
        this.regno = regno;
    }
    public Client(String regno, String firstname, String lastname, String phone, String email, String category, String photo) {
       this.regno = regno;
       this.firstname = firstname;
       this.lastname = lastname;
       this.phone = phone;
       this.email = email;
       this.category = category;
       this.photo = photo;
    }
   
    public String getRegno() {
        return this.regno;
    }
    
    public void setRegno(String regno) {
        this.regno = regno;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }




}


