package model;
// Generated May 12, 2020 12:37:21 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Operation generated by hbm2java
 */
public class Operation  implements java.io.Serializable {


     private Integer opid;
     private String clientname;
     private String bookname;
     private String author;
     private Date returndate;
     private String status;

    public Operation() {
    }

    public Operation(String clientname, String bookname, String author, Date returndate, String status) {
       this.clientname = clientname;
       this.bookname = bookname;
       this.author = author;
       this.returndate = returndate;
       this.status = status;
    }
   
    public Integer getOpid() {
        return this.opid;
    }
    
    public void setOpid(Integer opid) {
        this.opid = opid;
    }
    public String getClientname() {
        return this.clientname;
    }
    
    public void setClientname(String clientname) {
        this.clientname = clientname;
    }
    public String getBookname() {
        return this.bookname;
    }
    
    public void setBookname(String bookname) {
        this.bookname = bookname;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public Date getReturndate() {
        return this.returndate;
    }
    
    public void setReturndate(Date returndate) {
        this.returndate = returndate;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


